name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      user-service-condition: ${{ steps.check.outputs.user-service-condition }}
      order-service-condition: ${{ steps.check.outputs.order-service-condition }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: diff
        run: |
          echo "Comparing ${{ github.event.before }} -> ${{ github.sha }}"
          git fetch origin ${{ github.event.before }} --depth=1 || true
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > files.txt
          echo "Changed files:"
          cat files.txt

      - name: Evaluate service changes
        id: check
        run: |
          if grep -q "^user-service/" files.txt; then
            echo "user-service-condition=true" >> $GITHUB_OUTPUT
          else
            echo "user-service-condition=false" >> $GITHUB_OUTPUT
          fi

          if grep -q "^order-service/" files.txt; then
            echo "order-service-condition=true" >> $GITHUB_OUTPUT
          else
            echo "order-service-condition=false" >> $GITHUB_OUTPUT
          fi

  build-user-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.user-service-condition == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR for user-service
        run: mvn -f user-service/pom.xml clean package -DskipTests

      - name: Stop old containers and rebuild user-service
        run: |
          docker compose down
          docker compose up -d --build user-service

  build-order-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.order-service-condition == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR for order-service
        run: mvn -f order-service/pom.xml clean package -DskipTests

      - name: Stop old containers and rebuild order-service
        run: |
          docker compose down
          docker compose up -d --build order-service
