name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-user-service:
    if: contains(join(fromJson(toJson(github.event.commits)).*.modified, ''), 'user-service/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn -f user-service/pom.xml clean package
      - run: docker build -t user-service:latest ./user-service
      - run: docker stop user-service || true && docker rm user-service || true && docker run -d --name user-service -p 8081:8080 user-service:latest


  build-order-service:
    if: contains(join(fromJson(toJson(github.event.commits)).*.modified, ''), 'order-service/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn -f order-service/pom.xml clean package
      - run: docker build -t order-service:latest ./order-service
